### PR TITLE
tested and fixed mobile app screens to clear minor bugs

### PR DESCRIPTION
**Pull request by Daniel-TheProgrammer**
Went through the mobile app screens and did fixes 

Tested them completely and made some changes recommended during production.
Hope this helps 

Thanks!

### CODE REVIEW

**Comment by Nirajn2311** [comment]
Hi, could you send a screenshot or a message with which warnings have been resolved?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Daniel-TheProgrammer** [comment]
Below shows all the warnings are cleared

Screenshot (129)

**Comment by Nirajn2311** [comment]
I'd like to see what the warnings were before your fixes as I've not seen any warnings regarding the import statements.

**Comment by Daniel-TheProgrammer** [comment]
@Nirajn2311 
There were numerous warnings before I created the PR 
You can check in debug and see.


I cant show you the warnings cause they are already fixed.

**Comment by Nirajn2311** [comment]
I see you're using the pre-release version of Flutter. That version may be giving the warnings you saw as we've not seen those errors in the latest stable version of Flutter. 

I'll be closing this PR now. Also more details of setting up the development environment is here - https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-mobile-app-locally

**Comment by Nirajn2311** [comment]
The latest stable version is 3.0.5 but from what I see in your screenshot you're using version 3.1.0-0.0.pre.819 which is a pre-release version.

**Comment by Daniel-TheProgrammer** [comment]
Ok

**Comment by Daniel-TheProgrammer** [comment]
What is your question please?

**Pull request closed without merging**
