### PR TITLE
feat: podcast api tests

### PR DESCRIPTION
**Pull request by Sembauke**

### CODE REVIEW

**Comment by Sembauke** [comment]
@ojeytonwilliams What do you think about Joi Schemas here? Is it redundant as we have everything types with TS?

**Comment by ojeytonwilliams** [comment]
@Sembauke I'm not sure.  Validating the data via Joi can be useful if you don't know for sure what shape it has (i.e. if it's from an external API) or if you need something more specific than a type. i.e. if you want to check that your strings match a particular pattern (e.g. UUID), I don't believe you can enforce that with types.

**Comment by Sembauke** [comment]
Thanks I will leave it as it is then.

**Review by Nirajn2311 — APPROVED** [review]
LGTM but just one doubt. Do you think it would be better if we added another `expect` for the third test which checks if the number of episodes is less than or equal to 20.

**Review by Nirajn2311 — APPROVED** [review]

**Pull request merged**
