### PR TITLE
chore(api): reduce container size

### PR DESCRIPTION
**Pull request by Nirajn2311**
Docker image is reduced to 144 from 228 mb

### CODE REVIEW

**Review by ojeytonwilliams — DISMISSED** [review]
The package changes look good, but shouldn't the lock file have been updated?

**Comment by Nirajn2311** [comment]
Good catch. I've updated the lock file.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks @Nirajn2311, this LGTM.

This PR made me think: it would be nice to a basic smoke test for this.  Just something that starts a container and pings the `/` path should be plenty.

**Comment by Nirajn2311** [comment]
@ojeytonwilliams  I've added a test which builds the image, waits 30s(to make sure the container is up and running) and then pings(or curls to be exact) it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Inefficient

**Review by ojeytonwilliams — APPROVED** [review]
This is such an elegant solution - nice work!

It's unrelated to this PR, but do you both a `/` and a `/ping` route?  They seem to serve the same purpose to me.  Regardless, this PR looks great :+1:

**Comment by Nirajn2311** [comment]
Nice, I didn't realize there was a `/ping` endpoint. I've removed the other one and updated the action to use the `/ping` endpoint.

**Review by ojeytonwilliams — APPROVED** [review]
Cheers, LGTM :+1:

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
