### PR TITLE
refactor: fix lint issues in routes

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Hi again @Nirajn2311 Another day, another bit of refactoring!

This time I stopped because I wasn't sure how you wanted to handle missing Podcasts or Episodes.  I just made it throw, for now, to keep TypeScript happy.

### CODE REVIEW

**Review by raisedadead — COMMENTED** [review]
While you are here can you add a quick nodejs workflow based on this: 

https://github.com/freeCodeCamp/news/blob/main/.github/workflows/node.js-test.yml

You can comment the tests part.

**Comment by ojeytonwilliams** [comment]
I'll create another PR, if that's okay. This one makes some (modest) code changes and I'd rather not mix them up.

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/mobile/pull/292 is ready to be merged once all the linting issues have been dealt with.  Or now if we don't care about seeing red crosses for a few days.

**Review by Nirajn2311 — DISMISSED** [review]
There are still some lint issues in this file. Also there are some typescript errors in the file.

**Comment by ojeytonwilliams** [comment]
@Nirajn2311 yep, there are. I didn't want to continue without knowing how you'd like to handle errors.

I'm thinking the best approach is probably to use, say, Sentry.  Then we can send a report if something weird happens, but still try and serve *something* even in that case.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
