### PR TITLE
Update README with links to download the APK

### PR DESCRIPTION
**Pull request by Poussinou**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
Hi,

This small PR adds a button to get your app via Google Play, and another button to get the app on [IzzyOnDroid open source app repo](https://apt.izzysoft.de/fdroid/) in a F-Droid client. It also adds a link to get the latest APK from the Releases Section.

The link to IzzyOnDroid repo will help people without Google Play to find and use your app, as well as helping them to keep it updated.

Since the apk provided by IzzyOnDroid is simply taken from the Release Section of this repo, please never forget to attach your signed apk to the release when tagging a new version, so that Izzy can take it and make it available via a F-Droid client to your users !

### CODE REVIEW

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
@Poussinou Are the releases on F-droid updated manually or automatic?

**Comment by Poussinou** [comment]
>  Are the releases on F-droid updated manually or automatic?

This app is not available in the official F-Droid repo. It's rather available via the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) repo, which is compatible with a F-Droid client. I believe @izzysoft as an automatic update checker that runs every day or so. He might take your APK form the [Releases Section](https://github.com/freeCodeCamp/mobile/releases).

We can try to add your app to the official F-Droid repo if you want.

**Comment by IzzySoft** [comment]
Principially true as @Poussinou put it, with a minor adjustment. From the maintainer notes:

> * 2023-04-01 disabling updates completely as v3 now is not only beyond 30M per APK, but also brings a load of offenders (Crashlytics, Firebase Analytics & Co) https://github.com/freeCodeCamp/mobile/issues/891

So with those it wouldn't even stand a chance to be listed with F-Droid.org, sorry. But if the referenced issue is solved, auto-updates can be re-enabled in my repo again, @Sembauke.

**Comment by Sembauke** [comment]
I heard from the team we might be interested in the future but not right now. Would you be for deleting the custom app store image @Poussinou ?

**Comment by Poussinou** [comment]
> I heard from the team we might be interested in the future but not right now. Would you be for deleting the custom app store image @Poussinou ?

I believe if you don't provide an APK without so many trackers in a short future, you should remove the button to IzzyOnDroid store, but at least keep the one to Google Play, and absolutely keep the link to download the app from the releases sections, as it's now the only way to get your app if you don't have Google Play installed.

**Comment by IzzySoft** [comment]
> I believe if you don't provide an APK without so many trackers in a short future, you should remove the button to IzzyOnDroid store

Especially as the app is removed there already. I gladly reinstate it once the issue is solved – but until then the link would just produce a 404.

**Comment by Sembauke** [comment]
> I believe if you don't provide an APK without so many trackers in a short future, you should remove the button to IzzyOnDroid store, but at least keep the one to Google Play, and absolutely keep the link to download the app from the releases sections, as it's now the only way to get your app if you don't have Google Play installed.

Yes, that is true. We will have the app on IOS soon though.

**Comment by Nirajn2311** [comment]
> I believe if you don't provide an APK without so many trackers in a short future, you should remove the button to IzzyOnDroid store, but at least keep the one to Google Play, and absolutely keep the link to download the app from the releases sections, as it's now the only way to get your app if you don't have Google Play installed.

Hi, you are right and so we requested you to update your PR to remove the link to IzzySoft site. We need the Play Store link and we won't be removing the APK from the releases section.

In the future when the app is more self sustaining then we can think of keeping two flavors of the app.

**Comment by Sembauke** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
