### PR TITLE
moved variables outside build() method

### PR DESCRIPTION
**Pull request by mehade369**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

### variable -
Having the `views` and `titles` variables inside the `build()` method is a side effect and causes unnecessary variable calls.

I have moved the `views` and `titles` variables outside the `build()` method, and made them `static const`.

### IndexedStack -
I have warped the body Widgets inside `IndexedStack` which caches the children widgets state and prevents loading Widget in every time the `BottomNavigationBar` changes.

### CODE REVIEW

**Comment by Sembauke** [comment]
Hi this is looking good, 

We do not want the pubspec file to be in your pull request though, can you remove it?

**Comment by mehade369** [comment]
> Hi this is looking good,
> 
> We do not want the pubspec file to be in your pull request though, can you remove it?

I have deleted the `pubspec` from my code.

**Comment by Sembauke** [comment]
You deleted the file entirely, I meant to not include it in the pull-request 😄

**Comment by Sembauke** [comment]
So you would have to revert your commits and not include your pubspec file

**Pull request closed without merging**
