### PR TITLE
fix: auto dismiss toast for unavailable superblocks

### PR DESCRIPTION
**Pull request by Sanket6652**
… #1167

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

- I have solved issue  #1167 In the Learn section clicking an unsupported cert/path permanent pop-up. 
- fixed this by adding future delay to snackbar
untitled

### CODE REVIEW

**Comment by Sembauke** [comment]
This looks to be working great, could you up the delay to 2.5 seconds?

**Comment by Sanket6652** [comment]
added 2.5 sec delay

**Comment by Nirajn2311** [comment]
The analyzer has reported some errors in your code. You can view them by running `flutter analyze`.

**Review by Nirajn2311 — DISMISSED** [review]
The analyzer has reported some errors in your code. You can view them by running `flutter analyze`.

**Review by Sembauke — APPROVED** [review]

**Comment by Sembauke** [comment]
Thanks for the help @Sanket6652!

**Pull request merged**
