### PR TITLE
feat: flutter 3.16

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

### CODE REVIEW

**Comment by Sembauke** [comment]
There seems to be an issue in the CI https://github.com/freeCodeCamp/mobile/actions/runs/8282205693/job/22662503298?pr=1171


I am guessing that it has to do with the workflows not being up to date.

**Comment by Sembauke** [comment]
I am getting the following warnings locally:
1.
```
'describeEnum' is deprecated and shouldn't be used. Use the `name` getter on enums instead. This feature was deprecated after v3.10.0-1.1.pre.
Try replacing the use of the deprecated member with the replacement.
```
2.
```
'WillPopScope.new' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre.
Try replacing the use of the deprecated member with the replacement.
```

<details><summary>Flutter Doctor (unofficial channel)</summary>
<p>

```
[!] Flutter (Channel [user-branch], 3.16.9, on macOS 14.0 23A344 darwin-arm64, locale en-NL)
    ! Flutter version 3.16.9 on channel [user-branch] at /Users/sembauke/Documents/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (1 available)
[✓] Network resources
```
</p>
</details>

**Comment by Nirajn2311** [comment]
> There seems to be an issue in the CI [freeCodeCamp/mobile/actions/runs/8282205693/job/22662503298?pr=1171](https://github.com/freeCodeCamp/mobile/actions/runs/8282205693/job/22662503298?pr=1171)
> 
> I am guessing that it has to do with the workflows not being up to date.

Nice catch. Yea, I hadn't updated the workflows. It had slipped my mind 🤦

**Comment by Nirajn2311** [comment]
> I am getting the following warnings locally:

Strange. I got rid of those two deprecation warnings already. Could you say from which files those warnings are coming from?

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
