### PR TITLE
feat: python certification

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

A wild 🐍  is slithering into the app

TODO:
- [x] Separate out challenge view for each challenge type

### CODE REVIEW

**Comment by Nirajn2311** [comment]
Weird, the latest 2 commits were not showing up in the PR even though they were present in the branch.

**Comment by Nirajn2311** [comment]
The following superblocks can be enabled when this PR is in:
* Scientific Computing with Python
* Data Analysis with Python
* Machine Learning with Python

**Comment by Sembauke** [comment]
> The following superblocks can be enabled when this PR is in:
> 
> * Scientific Computing with Python
> * Data Analysis with Python
> * Machine Learning with Python

I have enabled them in this pull-request https://github.com/freeCodeCamp/freeCodeCamp/pull/50832

**Comment by Sembauke** [comment]
Something is wrong with making request when trying to complete a challenge

<details><summary>Details</summary>
<p>

[log] Setting screen to /challenge-view/5e6a54c358d3af90110a60a3
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  https://www.freecodecamp.dev/curriculum-data/submit-types.json
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  https://www.freecodecamp.dev/curriculum-data/submit-types.json
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  https://www.freecodecamp.dev/curriculum-data/submit-types.json
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ GET ║ Status: 200 OK
flutter: ║  https://www.freecodecamp.dev/curriculum-data/submit-types.json
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ GET ║ Status: 200 OK
flutter: ║  https://www.freecodecamp.dev/curriculum-data/submit-types.json
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ GET ║ Status: 200 OK
flutter: ║  https://www.freecodecamp.dev/curriculum-data/submit-types.json
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ POST
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ POST
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ POST
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ POST
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ POST ║ Status: 200 OK
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ POST ║ Status: 200 OK
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ POST ║ Status: 200 OK
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ POST ║ Status: 200 OK
flutter: ║  https://api.freecodecamp.dev/modern-challenge-completed
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  https://api.freecodecamp.dev/user/get-session-user
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter:
flutter: ╔╣ Response ║ GET ║ Status: 200 OK
flutter: ║  https://api.freecodecamp.dev/user/get-session-user
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
[log] {"points":18,"alreadyCompleted":true,"completedDate":1688541080380,"savedChallenges":[]}


</p>
</details>

**Comment by Nirajn2311** [comment]
> Something is wrong with making request when trying to complete a challenge

Yes this has been there since the beginning. For some reason, the requests get repeatedly sent even though the class is a singleton.

**Comment by Sembauke** [comment]
> > Something is wrong with making request when trying to complete a challenge
> 
> Yes this has been there since the beginning. For some reason, the requests get repeatedly sent even though the class is a singleton.

We need to fix this before the release.

**Comment by Nirajn2311** [comment]
That has to be done in a different PR as it's not in the scope of this one

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
