### PR TITLE
fix: remove unused duration property

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Hey @Nirajn2311, mostly this just defines and fixes up types, but `duration` doesn't seem to exist in the feed, so I dropped it from the Episode model.  This felt pretty serious, so I thought I'd create the PR as is so you could take a look.

### CODE REVIEW

**Comment by Nirajn2311** [comment]
> `duration` doesn't seem to exist in the feed

Could you give an example as `duration` is needed in the app.

**Comment by ojeytonwilliams** [comment]
@Nirajn2311 I'm not sure how I missed the duration, sorry about that!  I've put it back and used a custom item to keep TypeScript happy.

**Comment by ojeytonwilliams** [comment]
It's possible that's what I saw, yeah. 

So, the duration definitely *can* be there, but might not be?  As long as the app is okay with that, then I think the types are fine.

**Comment by Nirajn2311** [comment]
Yes, the duration will definitely be there but because of one episode I made it optional just in case any new episodes also miss out that property

**Comment by ojeytonwilliams** [comment]
Sorry for the delay, @Nirajn2311, but this should be ready to review now.

**Comment by Nirajn2311** [comment]
Thanks, I'll review it now

**Review by Nirajn2311 — APPROVED** [review]

**Pull request merged**
