### PR TITLE
feat: message not logged in users to login to comment on a topic

### PR DESCRIPTION
**Pull request by Sembauke**

### CODE REVIEW

**Review by Nirajn2311 — COMMENTED** [review]
Two things to add:
1) if the login with 2FA is not successful then the dialog should close and the login page should be shown with an error msg. Currently it closes the login page as a whole when 2FA code is wrong
2) After the user is logged in, the view should be updated the user should see the comment textbox. Currently it still showed the LOGIN button even after logging in

**Comment by Sembauke** [comment]
> if the login with 2FA is not successful then the dialog should close and the login page should be shown with an error msg. Currently it closes the login page as a whole when 2FA code is wrong

To be honest I think the 2FA dialog reappearing is intuitive enough to tell the user that the code was wrong. 

> After the user is logged in, the view should be updated the user should see the comment textbox. Currently it still showed the LOGIN button even after logging in

This is hard to do as cross page state management is very hard in flutter.

**Comment by Nirajn2311** [comment]
> To be honest I think the 2FA dialog reappearing is intuitive enough to tell the user that the code was wrong.

Here the dialog doesn't reappear. The whole thing just closes. 

> This is hard to do as cross page state management is fairly hard in flutter.

Hmm then it's fine for now. But it needs to be fixed/changed in the future as it will give a wrong message to the users.

**Review by Nirajn2311 — APPROVED** [review]

**Comment by Nirajn2311** [comment]
We have to look into cross page state management so that the login message disappears after the user logs in.

**Pull request merged**
