### PR TITLE
chore: migrate code to flutter 3.10

### PR DESCRIPTION
**Pull request by Nirajn2311**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

### CODE REVIEW

**Comment by Nirajn2311** [comment]
PR is blocked until `flutter_html` package is upgraded to the next stable version.

**Comment by Sembauke** [comment]
flutter_html will be in beta for a while. It should be fine.

**Comment by Nirajn2311** [comment]
Blocking it until Flutter fixes scroll issues

**Comment by Nirajn2311** [comment]
PhoneIDE PR https://github.com/freeCodeCamp/PhoneIDE/pull/53 has to go in first before this can be merged

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
