### PR TITLE
feat: better syntax highlighting for descriptions and instructions

### PR DESCRIPTION
**Pull request by Sembauke**
This adds better highlighting in the learn component. The readability is now better for both instructions and description.

It uses the highlightingView plugin that is already used for some of the aspects in news / learn.

Now instead of only highlighting the syntax that is normally highlighted by Prisma. It now highlights everything. Instead of having a boring container, with a bad font. 

We should also consider different themes for the highlighter. This one is now set to `atom-one-dark` 
Before:

image

After:

image

### CODE REVIEW

**Review by Nirajn2311 — DISMISSED** [review]
Everything LGTM but the text is not selectable yet and the PR for it in the respective package hasn't been merged after staying open for over a year

**Comment by Sembauke** [comment]
Hey @Nirajn2311,

Thanks for pointing that out. What do you think we should do?

**Comment by Sembauke** [comment]
I went ahead and did the following:

1. forked the syntax highlighting plugin (should be fine because it has not been updated in years)
2. checked out the pull request, made by one of the users of the package.
3. pushed the change to my fork

To test this out you need to do the following:
You need to link phoneIDE to your local path otherwise it will cause conflicts with the new version of the highlighter.
after this you can get and run. 

let me know what you think of it.

cc: @Nirajn2311

**Comment by Sembauke** [comment]
https://github.com/freeCodeCamp/PhoneIDE/pull/23

**Review by Nirajn2311 — APPROVED** [review]

**Pull request merged**
