### PR TITLE
fix: cursor position after using markdown formatting

### PR DESCRIPTION
**Pull request by Nirajn2311**

### CODE REVIEW

**Comment by Sembauke** [comment]
Hey @Nirajn2311,
The text in the comment box appears to be white or just no there.

Can you take a look?

picture:
image

**Comment by Nirajn2311** [comment]
I'm working on that fix. I know that issue is from the Theme file. I'm not sure how that got missed or if a later PR broke it.

**Comment by Sembauke** [comment]
> I'm working on that fix. I know that issue is from the Theme file. I'm not sure how that got missed or if a later PR broke it.

You should not change the theme though. You should just overwrite the text color on the Textfield directly.

**Comment by Nirajn2311** [comment]
I've fixed the text color but the text selection color is also white. The only way of changing that is by doing it like this - https://stackoverflow.com/questions/54656386/change-the-highlight-color-of-selected-text

Now that will be a pain if we have to keep setting the color everytime and the root cause for this is the ThemeData commit. 
Here is how the cursor color is set - https://api.flutter.dev/flutter/material/TextField/cursorColor.html

**Comment by Sembauke** [comment]
We can set the default color in the theme as shown here.
https://docs.flutter.dev/release/breaking-changes/text-selection-theme

This means we do not have to manually change color everytime.

**Review by Sembauke — APPROVED** [review]

**Pull request merged**
