### PR TITLE
feat: better news ui

### PR DESCRIPTION
**Pull request by Sembauke**

### CODE REVIEW

**Comment by Sembauke** [comment]
Sorry for changing this again. But after learning some new stuff from the forum feed pr I decided to implement some changes here also.

**Comment by Nirajn2311** [comment]
Could you add a screenshot also just so I know what I'm looking at when reviewing the PR.

**Comment by Sembauke** [comment]
image

**Review by Nirajn2311 — APPROVED** [review]

**Comment by Nirajn2311** [comment]
You can make use of `ListView.serparated` to get a list with separation(this will act as a border between the list items) between them. So then you won't have to add in a separate border to the `Container`.

**Pull request merged**
